# Generated by Django 5.2.7 on 2025-11-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrecord',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
