# Generated by Django 5.2.7 on 2025-11-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_borrowrecord_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='total_quantity',
            field=models.IntegerField(default=10),
        ),
    ]
