# Generated by Django 5.2.8 on 2025-11-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_staff_remove_userprofile_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STAFF', 'Staff')], default='STAFF', max_length=20),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
