# Generated by Django 5.2.8 on 2025-11-21 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_staff_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='password',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
