# Generated by Django 5.2.8 on 2025-11-21 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_asset_total_quantity'),
        ('inventory', '0008_staff_password'),
    ]

    operations = [
    ]
