# Generated by Django 5.2.8 on 2025-11-22 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_asset_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
