# Generated by Django 5.2.8 on 2025-11-23 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_asset_created_at_alter_asset_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='asset',
            name='serial_number',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
