# Generated by Django 5.2.8 on 2025-11-23 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alter_asset_id_alter_asset_serial_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisposalRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('reason', models.CharField(choices=[('DAMAGED', 'Damaged Beyond Repair'), ('OBSOLETE', 'Obsolete'), ('END_OF_LIFE', 'End of Life'), ('LOST', 'Lost/Missing'), ('OTHER', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('disposal_date', models.DateField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disposal_records', to='inventory.asset')),
                ('disposed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disposal_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
