# Generated by Django 5.2.7 on 2025-11-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_maintenancerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerecord',
            name='quantity',
            field=models.IntegerField(default=1, help_text='Number of items requiring maintenance'),
        ),
    ]
